[build]
  publish = "."
  functions = "netlify/functions"

# Pretty URLs for root files
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

# Always serve index if path not found (optional, keep if you have SPA)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
[[redirects]]
  from = "/verify"
  to = "/.netlify/functions/verify"
  status = 200
  force = true
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["ids.json"]

[[redirects]]
  from = "/verify"
  to = "/.netlify/functions/verify"
  status = 200
  force = true
