[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["ids.json"]

# pretty URLs for root files
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

# map short /verify to the function
[[redirects]]
  from = "/verify"
  to = "/.netlify/functions/verify"
  status = 200
  force = true
